name: 'QA'

'on':
    push:
        branches:
            - '4.x'
    pull_request:
        branches:
            - '4.x'

jobs:
    Build:
        env:
            COMPOSER_NO_INTERACTION: '1'
            COMPOSER_MEMORY_LIMIT: '-1'
            COMPOSER_DISABLE_XDEBUG_WARN: '1'
            #COMPOSER_CACHE_DIR: '/home/me/.cache/composer'

        runs-on: 'ubuntu-latest'

        steps:
            -
                uses: 'actions/checkout@v2'
            -
                name: 'Setup PHP'
                uses: 'shivammathur/setup-php@v2'
                with:
                    php-version: '8.1'
            -
                run: |
                    composer install --no-progress
            -
                run: |
                    "$(composer config bin-dir)/phpcs"
            -
                run: |
                    "$(composer config bin-dir)/phpunit"
